---
- name: Create directory for motd package
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy motd config file
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/update-motd.d/00-header
    owner: root
    group: root
    mode: '0755'
  notify: 
    - Update motd
